### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by mdnazmulhasan27771** [FarhanShoukat/Wanderlust#1]
hi, if you need logo/icon for your project, please contact me. nazmulhasan27771@gmail.com . It's free for GitHub all project. thank you.

**Comment by Hassaan-Elahi** [comment]
Hello , I just saw your mail. Can you elaborate a bit more on that .

Thanks,
Hassaan

**Comment by mdnazmulhasan27771** [comment]
I'm a graphic designer. If you want, I can free the logo / icon for your project.

**Comment by Hassaan-Elahi** [comment]
Yeah sure, I would like to avail this opportunity. It is a trip diary with
the ability to drop note at a particular place. So can you design a logo
for that.
